
name: learning-github-actions
run-name: ${{ github.actor }} is learning GitHub learning-github-actions

on:
  push:
    branches:
      - dev
    
  pull_request:
    branches:
      - dev
      - 'feature/*'

jobs:
  print-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print details
        run: |
          echo 'github.ref = '  ${{ github.ref }}
          echo 'github.ref_name = ' ${{ github.ref_name }}
